# Generated by Django 5.2.12 on 2026-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_options_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Aplicaciones Web', 'Aplicaciones Web'), ('Análisis de Negocios', 'Análisis de Negocios'), ('Inteligencia Artificial', 'Inteligencia Artificial'), ('Automatización', 'Automatización'), ('Robótica', 'Robótica')], default='Aplicaciones Web', max_length=50, verbose_name='Categoría'),
        ),
    ]
