# Generated by Django 5.2.12 on 2026-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Aplicaciones Web', 'Aplicaciones Web'), ('Análisis de Negocios', 'Análisis de Negocios'), ('Inteligencia Artificial', 'Inteligencia Artificial'), ('Automatización', 'Automatización'), ('Robótica', 'Robótica'), ('Desarrollo de Videojuegos', 'Desarrollo de Videojuegos')], default='Aplicaciones Web', max_length=50, verbose_name='Categoría'),
        ),
    ]
