# Generated by Django 5.2.12 on 2026-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Culminado', 'Culminado'), ('En progreso', 'En progreso'), ('Abandonado', 'Abandonado')], default='Culminado', max_length=20, verbose_name='Estado'),
        ),
    ]
