# Generated by Django 5.2.12 on 2026-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Industria'),
        ),
    ]
